services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: outdoor-spot-db
    env_file:
      - ./.env
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - outdoor-spot
    expose:
      - "5432"


  # Backend (Node.js + Prisma)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: outdoor-spot-backend
    working_dir: /app
    env_file:
      - ./.env
    environment:
      - PORT=${PORT}
#    ports:
#      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - postgres
    networks:
      - outdoor-spot
      - web




  # Frontend (Next.js)
  frontend:
    image: node:20-alpine
    container_name: outdoor-spot-frontend
    working_dir: /app
    env_file:
      - ./.env
    environment:
      - PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
#    ports:
#      - "3000:3000"
    expose:
       - "3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    depends_on:
      - backend
    network_mode: ""
    networks:
      outdoor-spot: {}
      web:
        aliases:
          - outdoor-spot-frontend
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
  frontend_next:

networks:
  outdoor-spot:
    driver: bridge
  web:
    external: true
