services:
  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  backend:
    ports:
      - "${PORT:-3001}:3001"
    networks:
      outdoor-spot: null

  frontend:
    network_mode: null
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      outdoor-spot: null
      web: null

networks:
  web: null
